name: 🐝 Feature request
description: Suggest a feature for this project
title: '🐝 Feature request'
labels: ['help wanted']
body:
  - type: markdown
    attributes:
      value: |
        NOTE: Each discrete (stand-alone) request should be in its own issue.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: 📖 Additional contex
      description: Add any other context or screenshots about the feature request here.


  - type: checkboxes
    attributes:
      label: 🧨 Issue Checklist
      description: Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.
      options:
        - label: I have checked for other similar issues
        - label: I have explained why this change is important
        - label: I have added necessary documentation (if appropriate)
    validations:
      required: true
